#!/bin/bash

if [ "$1" == "1" ]; then
  gnome-control-center bluetooth
fi

set -euo pipefail

PGM='
  NR == 1 { dev = $1 }
  NR == 3 { status = $1 }
  END { if (status == "UP") print dev }
'

function device-on() {
  test $(hciconfig | awk "$PGM")
}

function count-connected-devices() {
  hcitool con | tail +2 | wc -l
}

COLOR="#666666"
ICON=""
if device-on; then
  COUNT=$(count-connected-devices)
  if [ $COUNT -gt 0 ]; then
    ICON=""
  else
    ICON=""
  fi
  COLOR="#287AA9"
fi

echo "<span font='TerminessTTF Nerd Font 15'>$ICON</span>"
echo
echo $COLOR
