#!/bin/bash

if [ "$1" == "1" ]; then
  gnome-control-center wifi
fi

INTERFACE="${BLOCK_INSTANCE:-wlp9s0}"
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit

QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

CMD="\$1 == \"$INTERFACE\" { print \$4 }"
NAME=$(nmcli -terse -color no device | awk -F: "$CMD")

echo "   $NAME"
echo
# color
if [[ $QUALITY -ge 80 ]]; then
    echo "#39CCCC"
elif [[ $QUALITY -lt 80 ]]; then
    echo "#FFAE00"
elif [[ $QUALITY -lt 40 ]]; then
    echo "#FF4136"
fi
