#!/bin/bash
label="Disk Usage"
percent=$(df -h | awk '$6 == "/" { print $5 }' | sed s/%//)

echo " $label $percent% "
echo
echo "#000000"

color=
if [ $percent -lt 50 ]; then
  color="#fafafa"
else
  color="#feafea"
fi

echo $color
